export default {
    en: {
        summary: "I'm a software developer by heart and trade. I love solving the riddles of programming and while doing so implementing great user experiences envisioned by great designers.",
        exp: "Experience",
        creepybug_dream: "Living the Unity indie game development dream in my individual company:",
        melaz_overview: "Edu games and gamified interactive experiences:",
        melaz_react: "React Native apps & React web apps",
        melaz_api: "API integration",
        melaz_unity: "Unity edu games and VR experiences",
        jfg: "Unity internship",
        uni_title: "University of Bologna",
        uni_degree: "Master degree with honors in Computer Science:",
        uni_thesis: "Thesis:",
    },
    it: {
        summary: "Sono uno sviluppatore software per passione e mestiere. Amo risolvere gli enigmi della programmazione e nel farlo implementare splendide esperienze utente ideate da grandi designer.",
        exp: "Esperienza",
        creepybug_dream: "Il sogno dello sviluppatore di videogiochi indie Unity nella mia ditta individuale:",
        melaz_overview: "Edu games ed esperienze interattive gamificate:",
        melaz_react: "App React Native & web app React",
        melaz_api: "Integrazione API",
        melaz_unity: "Edu games in Unity ed esperienze VR",
        jfg: "Tirocinio Unity",
        uni_title: "Università di Bologna",
        uni_degree: "Laurea magistrale con lode in Informatica:",
        uni_thesis: "Tesi:",
    },
};