export default {
    en: {
        a11y_pic: "my picture",
        a11y_darkmode: "dark mode",
        summary: "I'm a software engineer by heart and trade. I love solving the riddles of programming and while doing so implementing great user experiences envisioned by great designers.",
        exp: "Experience",
        exp_from: "from",
        exp_endof: "late",
        exp_mid: "mid",
        exp_year: "year",
        exp_years: "years",
        exp_months: "months",
        exp_ongoing: "ongoing",
        creepybug_dream: "Living the Unity indie game development dream in my individual company:",
        melaz_overview: "Edu games and gamified interactive experiences:",
        melaz_react: "React Native apps & React web apps",
        melaz_api: "API integration",
        melaz_unity: "Unity edu games and VR experiences",
        jfg: "Unity internship",
        uni_title: "University of Bologna",
        uni_degree: "Bachelor & Master degree in Computer Science:",
        uni_grade: "Summa cum laude",
        uni_thesis: "Thesis:",
        updated: "Updated",
    },
    it: {
        a11y_pic: "la mia foto",
        a11y_darkmode: "tema scuro",
        summary: "Sono un software engineer per passione e mestiere. Amo risolvere gli enigmi della programmazione e nel farlo implementare splendide esperienze utente ideate da grandi designer.",
        exp: "Esperienza",
        exp_from: "da",
        exp_endof: "fine",
        exp_mid: "metà",
        exp_year: "anno",
        exp_years: "anni",
        exp_months: "mesi",
        exp_ongoing: "attuale",
        creepybug_dream: "Il sogno dello sviluppatore di videogiochi indie Unity nella mia ditta individuale:",
        melaz_overview: "Edu games ed esperienze interattive gamificate:",
        melaz_react: "App React Native e Web App React",
        melaz_api: "Integrazione API",
        melaz_unity: "Edu games in Unity ed esperienze VR",
        jfg: "Tirocinio Unity",
        uni_title: "Università di Bologna",
        uni_degree: "Laurea triennale e magistrale in Informatica (Scienze):",
        uni_grade: "110 e lode",
        uni_thesis: "Tesi:",
        updated: "Aggiornato",
    },
};